### ISSUE TITLE
Get a better name for this repo

### ISSUE THREAD

**Issue by myakove** [myakove/set-labels#20]

**Comment by sarahbx** [comment]
Suggestion: `protest`

We will PRoTest the code submitted if necessary. 🙂

**Comment by sarahbx** [comment]
`pit-stop` 🏁

**Comment by myakove** [comment]
@rnetser

**Comment by rnetser** [comment]
github-pr-workflows? pr-workflows? precheck-prs?

**Comment by sarahbx** [comment]
that is a persistent `p`.

**Comment by sarahbx** [comment]
`checkpoint`
`terminal`
`waypoint`

**Comment by rnetser** [comment]
Call me old fashioned but I prefer a more straight-forward name

**Comment by sarahbx** [comment]
fair enough 🙂 

reversing one of yours above...
`pr-precheck` ?

**Comment by myakove** [comment]
I like `pr-workflows` @sarahbx WDYT?

**Comment by sarahbx** [comment]
`pr-workflows` lgtm 👍

**Comment by myakove** [comment]
`pr-workflows` it is then.
